config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  # /:path
  resources :pages, path: '', only: [] do
    collection do
      get 'pricing'
      get 'about'
      get 'newsletter'
      get 'love'
      get 'feedback'
      get 'features'

      # For analytics
      post 'track_social'
      post 'track_time'
      post 'submit_feedback'
    end
  end

  scope module: :admin do
    # /metrics/:path
    resources :metrics, only: :index do
      collection do
        get 'newsletter'
        get 'traffic'
        get 'social'
      end
    end

    # /charts/:path
    resources :charts, only: [] do
      collection do
        get 'subscription_ratio'
        get 'subscription_by_date'
        get 'landing_page_feedback'

        get 'social_share_ratio'
        get 'social_share_by_date'

        get 'referrers_ratio'
        get 'referrers_by_date'
        get 'average_time_spent_per_page'
        get 'number_of_visits_per_page'

        get 'newsletter_subscription_by_date'
        get 'unsubscription_by_newsletter'
        get 'unsubscription_reason'
      end
    end

    # /newsletters/:path
    resources :newsletters, only: %i[index create new show] do
      collection do
        get 'subscribers'
        get 'unsubscribe'

        post 'subscribe'
        post 'unsubscribe', to: 'newsletters#post_unsubscribe'
      end
    end
  end

  namespace :admin do
    resources :dashboard, only: :index

    resources :categories, only: %i[index create update destroy]
    resources :skills, only: %i[index create update destroy]
  end

  resources :categories, only: :index
  resources :skills, only: :index

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # /users/:path
  resources :users, only: %i[index show] do
    member do
      get 'timeline'
    end
  end

  # /settings/:path
  scope module: :users do
    namespace :settings do
      resource :profile, only: %i[show update] do
        delete 'remove_avatar'
      end

      resource :account, only: :show do
        delete 'disconnect_omniauth'
        put 'reset_password'
      end

      resource :billing, only: %i[show update]

      resource :personality, only: %i[show update]

      resource :skills, only: %i[show create destroy]

      resource :emails, only: :show do
        post 'subscribe'
        post 'unsubscribe'
      end
    end
  end

  # /projects/:path
  resources :projects do
    get 'explore', on: :collection

    # TODO: change the name?
    member do
      get 'count'
      patch 'change_status'
    end

    scope module: :projects do
      scope module: :teams do
        resources :teams, except: %i[index]

        resources :manage, only: %i[index create] do
          collection do
            get 'suggest'
            get 'manage_data'
            post 'recompute_data'
            delete 'remove_user'
          end
        end
      end

      shallow do
        scope module: :appeals do
          resources :invitations, only: %i[index create destroy] do
            post 'accept', on: :member
          end

          resources :applications, only: %i[index create destroy] do
            post 'accept', on: :member
          end
        end
      end

      resources :tasks, except: %i[index show] do
        collection do
          get 'data'
        end

        member do
          patch 'set_percentage'
          patch 'assign_self'
        end
      end
    end
  end

  # /notifications/:path
  resources :notifications, only: %i[index destroy] do
    member do
      patch 'read'
      patch 'unread'
    end

    patch 'read_all', on: :collection
  end

  authenticated :user do
    root to: 'projects#index', as: :authenticated_root
  end

  root to: 'pages#home'
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

# controller for OAuth Devise
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def omniauth_flow
    user_signed_in? ? connect_flow : sign_in_flow

    return unless @user&.persisted?

    user_signed_in? ? connect_success_action : sign_in_success_action
  end

  Devise.omniauth_providers.each do |provider|
    alias_method provider, :omniauth_flow
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  private

  def sign_in_flow
    identity = User.sign_in_omniauth(request.env['omniauth.auth'])

    errors = identity.errors.full_messages + identity.user.errors.full_messages

    if errors.blank?
      @user = identity.user
    else
      flash[:toast_error] = errors
      redirect_to new_user_registration_url
    end
  end

  def connect_flow
    identity = current_user.connect_omniauth(request.env['omniauth.auth'])

    if identity.errors.blank?
      @user = identity.user
    else
      flash[:toast_error] = identity.errors.full_messages
      redirect_to settings_account_path
    end
  end

  def connect_success_action
    flash[:toast_success] = 'Account Connected'
    redirect_to settings_account_path
  end

  def sign_in_success_action
    sign_in @user
    redirect_to after_sign_in_path_for(@user)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

# Controller for setting and changing password
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    return head :ok if successfully_sent?(resource)

    render json: { message: resource.errors.full_messages }, status: :bad_request
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    yield resource if block_given?

    resource.errors.empty? ? update_success : update_fail
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end#

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  private

  def update_fail
    set_minimum_password_length
    render json: { message: resource.errors.full_messages }, status: :bad_request
  end

  def update_success
    resource.unlock_access! if unlockable?(resource)
    if Devise.sign_in_after_reset_password
      resource.after_database_authentication
      sign_in(resource_name, resource)
    end
    render js: "window.location='#{root_path}'"
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

# Controller for registration and update password
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    resource.persisted? ? register_success : register_fail
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    if form_filled?
      resource_updated = oauth_update_resource
      yield resource if block_given?
      resource_updated ? update_success : register_fail
    else
      render json: { message: 'Please fill in the form' }, status: :bad_request
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  #   root_path
  # end

  private

  def form_filled?
    params[:user][:password].present? && params[:user][:password_confirmation].present?
  end

  def register_success
    sign_up(resource_name, resource)
    render js: "window.location='#{root_path}'"
  end

  def update_success
    bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

    flash[:toast_success] = 'Password Changed'
    render js: "window.location='#{settings_account_path}'"
  end

  def register_fail
    clean_up_passwords resource
    set_minimum_password_length
    render json: { message: resource.errors.full_messages }, status: :bad_request
  end

  def oauth_update_resource
    if resource.password_automatically_set?
      resource.update(account_update_params)
    else
      update_resource(resource, account_update_params)
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

# Controller for handling user sessions
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate(auth_options)

    if resource
      sign_in(resource_name, resource)
      yield resource if block_given?
      render js: "window.location='#{after_sign_in_path_for(resource)}'"
    else
      set_flash_message(:errors, :invalid)
      render json: { message: flash[:errors] }, status: :unauthorized
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/settings/accounts_controller.rb
# frozen_string_literal: true

class Users::Settings::AccountsController < Users::Settings::BaseController
  def show
    render 'users/settings/account'
  end

  def disconnect_omniauth
    identity = current_user.identities.find_by!(provider: params[:provider])

    if disconnect_provider_allowed?
      identity.delete
      flash[:toast_success] = 'Account Disconnected'
    else
      flash[:toast_error] = 'Please set up a password before disabling all Social Accounts'
    end

    redirect_to settings_account_path
  end

  def reset_password
    current_user.send_reset_password_instructions
    flash[:toast_success] = 'Check your email for reset instruction'
    redirect_to settings_account_path
  end

  private

  def disconnect_provider_allowed?
    !current_user.password_automatically_set? || current_user.identities.size > 1
  end
end

app/controllers/users/settings/base_controller.rb
# frozen_string_literal: true

class Users::Settings::BaseController < ApplicationController
  layout 'user'
end

app/controllers/users/settings/billings_controller.rb
# frozen_string_literal: true

class Users::Settings::BillingsController < Users::Settings::BaseController
  def show
    render 'users/settings/billing'
  end

  def update
    current_user.license.update(plan: params[:plan])
    flash[:toast_success] = 'Billing plan updated'
  rescue ArgumentError
    flash[:toast_error] = 'Invalid argument'
  ensure
    redirect_to settings_billing_path
  end
end

app/controllers/users/settings/emails_controller.rb
# frozen_string_literal: true

class Users::Settings::EmailsController < Users::Settings::BaseController
  def show
    render 'users/settings/emails'
  end

  def subscribe
    NewsletterSubscription.subscribe(current_user.email)

    flash[:toast_success] = 'Newsletter Subscribed'
    redirect_to settings_emails_path
  end

  def unsubscribe
    NewsletterSubscription.find_by(email: current_user.email)&.unsubscribe

    flash[:toast_success] = 'Newsletter Unsubscribed'
    redirect_to settings_emails_path
  end
end

app/controllers/users/settings/personalities_controller.rb
# frozen_string_literal: true

# Controller for setting user personality
class Users::Settings::PersonalitiesController < Users::Settings::BaseController
  def show
    @personality = current_user.personality || Personality.new
    render 'users/settings/personalities'
  end

  def update
    # Invalid input will by rescued by StatementInvalid in ApplcationController
    current_user.update(personality: Personality.find_by(personality_params))

    flash[:toast_success] = 'Personality Updated'
    render js: "window.location = '#{settings_personality_path}'"
  end

  private

  def personality_params
    params.require(:personality).permit(:mind, :energy, :nature, :tactic)
  end
end

app/controllers/users/settings/profiles_controller.rb
# frozen_string_literal: true

class Users::Settings::ProfilesController < Users::Settings::BaseController
  def show
    render 'users/settings/profile'
  end

  def update
    if current_user.update(profile_params)
      render json: { message: 'Profile updated' }
    else
      render json: { message: current_user.errors.full_messages }, status: :bad_request
    end
  end

  def remove_avatar
    return head :not_found unless current_user.avatar.attached?

    current_user.avatar.purge_later

    redirect_to settings_profile_path, status: :found
  end

  private

  def profile_params
    params.require(:user).permit(:name, :avatar, :birthdate)
  end
end

app/controllers/users/settings/skills_controller.rb
# frozen_string_literal: true

class Users::Settings::SkillsController < Users::Settings::BaseController
  def show
    @skills = current_user.skills.with_category('category_name ASC, name ASC')
    render 'users/settings/skills'
  end

  def create
    # insert_all does not trigger validations, handle the errors on client-side
    records = UserSkill.insert_all(
      skill_params[:skill_ids].map { |id| { user_id: current_user.id, skill_id: id } }
    )

    if skill_params[:skill_ids].length == records.length
      head :ok
    else
      head :unprocessable_entity
    end
  end

  def destroy
    user_skill = current_user.user_skills.find_by!(skill_id: params[:skill_id])
    user_skill.delete ? head(:ok) : head(:bad_request)
  end

  private

  def skill_params
    params.require(:skill).permit(skill_ids: [])
  end
end

app/views/users/settings/account.haml
- content_for :title, 'Account settings'

.content.settings#account-settings
  .columns
    .column.is-4
      %h4.title.is-4 Change Password
    .column
      = form_with model: current_user, url: registration_path(current_user), method: :patch, html: { '@ajax:error': 'ajaxError' } do |f|
        - unless current_user.password_automatically_set?
          .field
            %label.label Old password
            .control
              = f.password_field :current_password, autocomplete: 'current-password', class: 'input', required: true
            %p.help You must provide your current password in order to change it.
        .field
          %label.label New password
          .control
            = f.password_field :password, autocomplete: 'new-password', class: 'input', required: true
            %p.help Minimum #{Devise.password_length.min} characters
        .field
          %label.label Confirm new password
          .control
            = f.password_field :password_confirmation, autocomplete: 'new-password', class: 'input', required: true

        .field.is-grouped.is-grouped-multiline.items-center
          .control
            = f.submit 'Save password', class: 'button is-success'
          .control
            = link_to 'I forgot my password', reset_password_settings_account_path, method: :put,
              data: { disable_with: 'Sending email...' }
  .columns
    .column.is-4
      %h4.title.is-4 Social Accounts
    .column
      .flex.flex-wrap
        - Devise.omniauth_providers.each do |provider|
          .buttons.has-addons.mr-5.mb-3
            .button.is-static{ class: provider_label(provider) }
              %span.icon
                %span.iconify.is-24{ 'data-icon': provider_icon(provider) }
              %span.has-text-black= provider_label(provider)
            - if current_user.oauth_provider_connected?(provider)
              = button_to 'Disconnect', disconnect_omniauth_settings_account_path(provider: provider), method: :delete,
                class: 'button has-text-danger font-semibold', data: { disable: true }
            - else
              = button_to 'Connect', omniauth_authorize_path(current_user, provider), class: 'button', data: { disable: true }
  .columns
    .column.is-4
      %h4.title.is-4.has-text-danger Delete account
    .column
      %p Once you delete your account, there is no going back. Please be certain.
      = button_to 'Delete my account', registration_path(current_user), method: :delete,
        class: 'button is-danger', data: { disable: true, confirm: 'Are you sure?' }

app/views/users/settings/billing.haml
- content_for :title, 'Billing'

.content#billing-setting
  %h4.title.is-4 Billing

  .columns.flex-wrap
    .column
      .card
        %header.card-header.has-background-white-ter
          .card-header-title.justify-between
            Free Plan
            - if current_user.license.free?
              %p.has-text-grey Current Plan
        .card-content
          .price-per-month
            %p.price £0
            %p.condition monthly
          .price-per-year.is-invisible
            billed annually at £0
          %hr
          %ul
            %li Join unlimited projects
            %li Automated team building
            %li Skill set manager

        %footer.card-footer.has-background-white-ter
          - if current_user.license.free?
            %button.button{ disabled: true } Upgrade
          - else
            = button_to 'Downgrade', settings_billing_path(plan: 'free'), method: :put,
              class: 'button is-success', data: { disable: true }
    .column
      .card
        %header.card-header.has-background-white-ter
          .card-header-title.justify-between
            Pro Plan
            - if current_user.license.pro?
              %p.has-text-grey Current Plan
        .card-content
          .price-per-month
            %p.price £15
            %p.condition monthly
          .price-per-year
            billed annually at £180
          %hr
          %ul
            %li.font-bold All Free features
            %li Unlimited private projects
            %li Automated task allocation

        %footer.card-footer.has-background-white-ter
          - if current_user.license.pro?
            %button.button{ disabled: true } Upgrade
          - else
            = button_to current_user.license.ultimate? ? 'Downgrade' : 'Upgrade',
              settings_billing_path(plan: 'pro'), method: :put,
              class: 'button is-success', data: { disable: true }
    .column
      .card
        %header.card-header.has-background-white-ter
          .card-header-title.justify-between
            Ultimate Plan
            - if current_user.license.ultimate?
              %p.has-text-grey Current Plan
        .card-content
          .price-per-month
            %p.price £20
            %p.condition monthly
          .price-per-year
            billed annually at £240
          %hr
          %ul
            %li.font-bold All Pro features
            %li Unlimited members per projects
            %li Unlimited active tasks

        %footer.card-footer.has-background-white-ter
          - if current_user.license.ultimate?
            %button.button{ disabled: true } Upgrade
          - else
            = button_to 'Upgrade', settings_billing_path(plan: 'ultimate'), method: :put,
              class: 'button is-success', data: { disable: true }

app/views/users/settings/emails.haml
- content_for :title, 'Email settings'

.content.settings
  .columns
    .column.is-4
      %h4.title.is-4 Newsletter Preferences
    .column
      - if current_user.newsletter_subscribed?
        %p Are you sure? You will miss out the latest news and features!
        = button_to 'Unsubscribe Newsletter', unsubscribe_settings_emails_path, class: 'button is-warning', data: { disable: true }
      - else
        %p Receive the latest news from our company.
        = button_to 'Subscribe Newsletter', subscribe_settings_emails_path, class: 'button', data: { disable: true }

app/views/users/settings/personalities.haml
- content_for :title, 'Personality settings'

.content.settings
  .columns
    .column.is-4
      %h4.title.is-4.mb-3 Personality
      %p
        Learn more about your personality type by following the
        = link_to 'personalities chart', 'https://upload.wikimedia.org/wikipedia/commons/1/1f/MyersBriggsTypes.png', target: '_blank', rel: 'noopener'
    .column
      - if current_user.personality
        %label.label Current personality
        %figure.image.mt-0
          .type= File.read("#{Rails.root}/public/images/personalities/#{current_user.personality.to_type.downcase}.svg").html_safe

          %h4.has-text-centered.mt-3= current_user.personality.to_type

      = form_with model: @personality, url: settings_personality_path, method: :patch, html: { '@ajax:error': 'ajaxError' } do |f|
        .field
          .control
            %label.label Are you outwardly or inwardly focused?
            .field
              = f.label :mind_i, class: 'b-radio radio' do
                = f.radio_button :mind, 'I', required: true
                %span.check
                %span.control-label Introversion (I)

            .field
              = f.label :mind_e, class: 'b-radio radio' do
                = f.radio_button :mind, 'E'
                %span.check
                %span.control-label Extraversion (E)

        .field
          .control
            %label.label How do you prefer to take information?
            .field
              = f.label :energy_s, class: 'b-radio radio' do
                = f.radio_button :energy, 'S', required: true
                %span.check
                %span.control-label Sensing (S)
            .field
              = f.label :energy_n, class: 'b-radio radio' do
                = f.radio_button :energy, 'N'
                %span.check
                %span.control-label Intuition (N)

        .field
          .control
            %label.label How do you prefer to make decisions?
            .field
              = f.label :nature_t, class: 'b-radio radio' do
                = f.radio_button :nature, 'T', required: true
                %span.check
                %span.control-label Thinking (T)
            .field
              = f.label :nature_f, class: 'b-radio radio' do
                = f.radio_button :nature, 'F'
                %span.check
                %span.control-label Feeling (F)

        .field
          .control
            %label.label How do you prefer to live your outer life?
            .field
              = f.label :tactic_j, class: 'b-radio radio' do
                = f.radio_button :tactic, 'J', required: true
                %span.check
                %span.control-label Judging (J)
            .field
              = f.label :tactic_p, class: 'b-radio radio' do
                = f.radio_button :tactic, 'P'
                %span.check
                %span.control-label Perception (P)

        .field
          .control
            = f.submit 'Save changes', class: 'button is-success'

app/views/users/settings/profile.haml
- content_for :title, 'Edit Profile'

= form_with model: current_user, url: settings_profile_path, method: :patch, html: { '@ajax:success': 'profileUpdateSuccess', '@ajax:error': 'ajaxError' } do |f|
  .content.settings#profile-settings
    .columns
      .column.is-4
        %h4.title.is-4.mb-3 Public Avatar
        %p You can change your avatar here or remove the current avatar to revert to gravatar.com
      .column
        %figure.image.is-128x128.user-avatar-container
          = image_tag user_avatar(current_user), alt: 'My avatar', id: 'avatar'

        %label.label Upload new avatar
        .file.has-name.my-3
          %label.file-label
            = f.file_field :avatar, accept: 'image/png,image/jpg,image/jpeg', class: 'file-input', '@change': 'avatarChanged'
            %span.file-cta
              %span.file-label
                Choose an image
            %span.file-name
              {{ avatarFilename }}
        %p.has-text-grey Maximum file size allowed is 200KB
        - if current_user.avatar.attached?
          %hr
          = link_to 'Remove avatar', remove_avatar_settings_profile_path, method: :delete, class: 'button is-danger is-outlined',
              data: { disable: true, confirm: 'Avatar will be removed. Are you sure?' }

    .columns
      .column.is-4
        %h4.title.is-4.mb-3 Main settings
        %p This information will be shown on your profile
      .column
        .field
          %label.label
            Name
            - if current_user.name.blank?
              %p.has-text-primary Add a name so people can easily identity you
          .control
            = f.text_field :name, class: 'input', maxlength: 255

        %label.label Date of Birth
        .field.is-grouped.is-grouped-multiline
          .control
            .select
              = f.date_select :birthdate, start_year: Time.current.year - 7, end_year: Time.current.year - 80,
                prompt: { day: 'Select day', month: 'Select month', year: 'Select year' },
                date_separator: '</div></div><div class="control"><div class="select">'
        .field
          .control
            = f.submit 'Update profile', class: 'button is-success'

app/views/users/settings/skills.haml
- content_for :title, 'Skill settings'

.content.settings#skill-settings
  .columns
    .column.is-4
      %h4.title.is-4.mb-3 Skills
      %p Add skills to your profile to showcase what you are good at.
    .column
      %skill{ ':init-skills': @skills.to_json }