config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  # /:path
  resources :pages, path: '', only: [] do
    collection do
      get 'pricing'
      get 'about'
      get 'newsletter'
      get 'love'
      get 'feedback'
      get 'features'

      # For analytics
      post 'track_social'
      post 'track_time'
      post 'submit_feedback'
    end
  end

  scope module: :admin do
    # /metrics/:path
    resources :metrics, only: :index do
      collection do
        get 'newsletter'
        get 'traffic'
        get 'social'
      end
    end

    # /charts/:path
    resources :charts, only: [] do
      collection do
        get 'subscription_ratio'
        get 'subscription_by_date'
        get 'landing_page_feedback'

        get 'social_share_ratio'
        get 'social_share_by_date'

        get 'referrers_ratio'
        get 'referrers_by_date'
        get 'average_time_spent_per_page'
        get 'number_of_visits_per_page'

        get 'newsletter_subscription_by_date'
        get 'unsubscription_by_newsletter'
        get 'unsubscription_reason'
      end
    end

    # /newsletters/:path
    resources :newsletters, only: %i[index create new show] do
      collection do
        get 'subscribers'
        get 'unsubscribe'

        post 'subscribe'
        post 'unsubscribe', to: 'newsletters#post_unsubscribe'
      end
    end
  end

  namespace :admin do
    resources :dashboard, only: :index

    resources :categories, only: %i[index create update destroy]
    resources :skills, only: %i[index create update destroy]
  end

  resources :categories, only: :index
  resources :skills, only: :index

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # /users/:path
  resources :users, only: %i[index show] do
    member do
      get 'timeline'
    end
  end

  # /settings/:path
  scope module: :users do
    namespace :settings do
      resource :profile, only: %i[show update] do
        delete 'remove_avatar'
      end

      resource :account, only: :show do
        delete 'disconnect_omniauth'
        put 'reset_password'
      end

      resource :billing, only: %i[show update]

      resource :personality, only: %i[show update]

      resource :skills, only: %i[show create destroy]

      resource :emails, only: :show do
        post 'subscribe'
        post 'unsubscribe'
      end
    end
  end

  # /projects/:path
  resources :projects do
    get 'explore', on: :collection

    # TODO: change the name?
    member do
      get 'count'
      patch 'change_status'
    end

    scope module: :projects do
      scope module: :teams do
        resources :teams, except: %i[index]

        resources :manage, only: %i[index create] do
          collection do
            get 'suggest'
            get 'manage_data'
            post 'recompute_data'
            delete 'remove_user'
          end
        end
      end

      shallow do
        scope module: :appeals do
          resources :invitations, only: %i[index create destroy] do
            post 'accept', on: :member
          end

          resources :applications, only: %i[index create destroy] do
            post 'accept', on: :member
          end
        end
      end

      resources :tasks, except: %i[index show] do
        collection do
          get 'data'
        end

        member do
          patch 'set_percentage'
          patch 'assign_self'
        end
      end
    end
  end

  # /notifications/:path
  resources :notifications, only: %i[index destroy] do
    member do
      patch 'read'
      patch 'unread'
    end

    patch 'read_all', on: :collection
  end

  authenticated :user do
    root to: 'projects#index', as: :authenticated_root
  end

  root to: 'pages#home'
end

app/controllers/projects/appeals/applications_controller.rb
# frozen_string_literal: true

class Projects::Appeals::ApplicationsController < Projects::Appeals::BaseController
  before_action :set_application, only: %i[accept destroy]

  def index
    project = Project.find(params[:project_id])
    authorize! project, with: Appeal::ApplicationPolicy

    render json: { applications: Appeal.application.list_in_project(project) }
  end

  def create
    @application = Appeal.new(user: current_user, project_id: params[:project_id], type: 'application')

    authorize! @application, with: Appeal::ApplicationPolicy
    return application_fail unless @application.save

    flash[:toast_success] = 'Application sent'
    render js: 'location.reload();'
  end

  def accept
    @application.project.unassigned_team.users << @application.user

    msg = @application.project.errors.full_messages
    return application_fail(msg) unless msg.blank? && @application.delete

    @application.send_resolve_notification('accept')
    head :ok
  end

  def destroy
    return application_fail unless @application.delete

    @application.send_resolve_notification('decline', current_user == @application.user)

    # TODO: should return JSON only, otherwise the Table will redirect
    flash[:toast_success] = 'Application deleted'
    render js: 'location.reload();'
  end

  private

  def application_fail(msg = @application.errors.full_messages)
    render json: { message: msg }, status: :unprocessable_entity
  end

  def set_application
    @application = Appeal.application.find(params[:id])
    authorize! @application, with: Appeal::ApplicationPolicy
  end
end

app/controllers/projects/appeals/base_controller.rb
# frozen_string_literal: true

class Projects::Appeals::BaseController < ApplicationController
  rescue_from ActionPolicy::Unauthorized do
    head :forbidden
  end
end

app/controllers/projects/appeals/invitations_controller.rb
# frozen_string_literal: true

class Projects::Appeals::InvitationsController < Projects::Appeals::BaseController
  before_action :set_invitation, only: %i[accept destroy]

  def index
    project = Project.find(params[:project_id])
    authorize! project, with: Appeal::InvitationPolicy

    render json: { invitations: Appeal.invitation.list_in_project(project) }
  end

  def create
    @invitation = Appeal.new(user: User.find_by(email: params[:email]),
                             project_id: params[:project_id],
                             type: 'invitation')

    authorize! @invitation, with: Appeal::InvitationPolicy
    return invitation_fail unless @invitation.save

    render json: { invitation: @invitation }
  end

  def accept
    @invitation.project.unassigned_team.users << @invitation.user

    msg = @invitation.project.errors.full_messages
    return invitation_fail(msg) unless msg.blank? && @invitation.delete

    @invitation.send_resolve_notification('accept')
    render js: 'location.reload();'
  end

  def destroy
    return invitation_fail unless @invitation.delete

    @invitation.send_resolve_notification('decline', current_user == @invitation.user)

    # TODO: should return JSON only, otherwise the Table will redirect
    flash[:toast_success] = 'Invitation deleted'
    render js: 'location.reload();'
  end

  private

  def invitation_fail(msg = @invitation.errors.full_messages)
    render json: { message: msg }, status: :unprocessable_entity
  end

  def set_invitation
    @invitation = Appeal.invitation.find(params[:id])
    authorize! @invitation, with: Appeal::InvitationPolicy
  end
end

app/controllers/projects/tasks_controller.rb
# frozen_string_literal: true

class Projects::TasksController < ApplicationController
  before_action :set_task,
                only: %i[edit update set_percentage assign_self destroy]
  before_action :set_project,
                except: %i[update destroy assign_self set_percentage]
  before_action :set_skills, only: %i[new edit]

  layout 'project'

  # GET /tasks/new
  def new
    @task = Task.new(project: @project)
    authorize! @project, to: :create_task?
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks
  def create
    authorize! @project, to: :create_task?
    @task = @project.tasks.build(create_params)

    if @task.save
      @task.skill_ids = params.dig(:task, :skill_ids)
      @task.user_ids =  params.dig(:task, :user_ids)
      task_success('Task created')
    else
      task_fail
    end
  end

  # PATCH/PUT /tasks/1
  def update
    @task.update(edit_params) ? task_success('Task updated') : task_fail
  end

  def assign_self
    return task_fail('Task is already Assigned') if @task.users.present?

    @task.users << current_user
    @task.send_picked_up_notification
    head :ok
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    head :ok
  end

  def data
    extend AvatarHelper

    return render_404 unless request.xhr? && valid_data_type?

    render json: {
      data: TaskBlueprint.render_as_json(
        authorized_scope(@project.tasks, as: @type).includes(users: [{ avatar_attachment: :blob }])
      )
    }
  end

  def set_percentage
    @task.update(edit_params) ? head(:ok) : task_fail
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_skills
    @skills = @project.category.skills.map { |s| [s.name, s.id] }

    team = current_user.teams.find_by(project: @project)
    @assignees = authorized_scope(
      @project.users,
      as: :assignee,
      scope_options: { team_id: team&.id, project: @project }
    )
  end

  def set_task
    @task = Task.find(params[:id])
    authorize! @task
  end

  def create_params
    params.require(:task)
          .except(:skill_ids, :user_ids)
          .permit(:name, :description, :priority)
          .merge(user: current_user)
  end

  def edit_params
    params.require(:task).permit(:description, :name,
                                 :percentage, :priority,
                                 skill_ids: [], user_ids: [])
  end

  def task_fail(message = @task.errors.full_messages)
    render json: { message: message }, status: :unprocessable_entity
  end

  def task_success(message)
    flash[:toast_success] = message
    render js: "window.location = '#{project_path(@task.project)}'"
  end

  def valid_data_type?
    authorize! @project, to: :count?

    @type = params[:type]&.to_sym
    %i[assigned unassigned active completed].include?(@type)
  end
end

app/controllers/projects/teams/base_controller.rb
# frozen_string_literal: true

class Projects::Teams::BaseController < ApplicationController
  layout 'project'

  private

  def set_team
    @team = Team.find(params[:id])
    authorize! @team
  end

  def set_skills
    @skills = Skill.where(category: @project.category)
                   .collect { |s| [s.name, s.id] }
  end

  def set_project
    @project = Project.find(params[:project_id])
    authorize! @project, to: :manage?
  end

  def team_success(message)
    flash[:toast_success] = message
    render js: "window.location = '#{project_manage_index_path(@project)}'"
  end

  def team_fail(message = @team.errors.full_messages)
    render json: { message: message }, status: :unprocessable_entity
  end
end

app/controllers/projects/teams/manage_controller.rb
# frozen_string_literal: true

class Projects::Teams::ManageController < Projects::Teams::BaseController
  before_action :set_project

  def index; end

  def manage_data
    return render_404 unless request.xhr?

    @data = User.teams_data(@project)
    compute = CompatibilityCompute.new(@project.teams,
                                       @project.unassigned_team)

    render json: {
      compatibility: @data.to_h { |u| [u.id, compute.call(u)] },
      data: @data.group_by(&:team_id),
      teams: @project.teams&.select(:id, :name, :team_size)
    }
  end

  def suggest
    return team_fail('Invalid Mode') unless %w[balance cohesion efficient].include?(params[:mode])

    suggestion = Suggest.new(User.teams_data(@project),
                             @project.teams.where.not(name: 'Unassigned'),
                             @project.unassigned_team,
                             params[:mode]).call
    render json: { data: suggestion }
  end

  # save_data
  def create
    data = Oj.load(params[:data])
    teams = @project.teams
    users = @project.users
    data.each do |id, members|
      new_team = teams.find { |x| x.id.to_s == id }
      next if new_team.nil?

      authorize! new_team, to: :manage?

      saving_loop(new_team, members, teams, users)
    end
    render json: { data: data }
  end

  def recompute_data
    return team_fail('Invalid Mode') unless %w[balance cohesion efficient].include?(params[:mode])

    i = Oj.load(params[:data])
    teams = @project.teams.find(i.keys)
    d = recompute_loop(i, teams, params[:mode])

    render json: { compatibility: d }
  end

  def remove_user
    user = User.find(params[:user_id])
    @team = user.teams.find_by(project: @project)
    return team_fail('Cannot remove owner') if user == @project.user

    @team.users.delete(user)
    head :ok
  end

  private

  def change_team(member, new_team, old_team)
    authorize! new_team, to: :manage?
    new_team.users << member
    old_team.users.delete(member)
  end

  def recompute_loop(input, teams, mode)
    data = {}
    compute = Recompute.new(teams, teams.find { |x| x.name == 'Unassigned' }, mode)

    input.each do |team_id, members|
      next if members.blank?

      data.merge!(
        compute.call(teams.find { |x| x.id.to_s == team_id }, input).to_h
      )
    end
    data
  end

  def saving_loop(new_team, members, teams, users)
    members.each do |m|
      next unless m['team_id'] != new_team.id

      target = users.find { |x| x.id == m['id'] }
      old_team = teams.find { |x| x.id == m['team_id'] }
      change_team(target, new_team, old_team)
      m['team_id'] = new_team.id
    end
  end
end

app/controllers/projects/teams/teams_controller.rb
# frozen_string_literal: true

class Projects::Teams::TeamsController < Projects::Teams::BaseController
  before_action :set_team, only: %i[edit show update destroy]
  before_action :set_project, except: %i[show]
  before_action :set_skills, only: %i[new edit]
  skip_before_action :authenticate_user!, only: %i[show]

  # GET /teams/new
  def new; end

  # GET /teams/1/edit
  def edit; end

  def show
    extend AvatarHelper

    return render_404 unless request.xhr?

    render json: { member: @team.users, skill: @team.skills&.select(:id, :name),
                   team: @team, images: get_avatars(@team.users.pluck('id')) }
  end

  # POST /teams
  def create
    @team = @project.teams.build(create_params)

    if @team.save
      @team.skill_ids = params[:team][:skill_ids]
      team_success('Team was successfully created')
    else
      team_fail
    end
  end

  # PATCH/PUT /teams/1
  def update
    @team.update(edit_params) ? team_success('Team Saved') : team_fail
  end

  # DELETE /teams/1
  def destroy
    @project.unassigned_team.users << @team.users
    @team.destroy
    head :ok
  end

  private

  def create_params
    params.require(:team).except(:skill_ids)
          .permit(:team_size, :project_id, :name)
  end

  def edit_params
    params.require(:team).permit(:team_size, :name, skill_ids: [])
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# Controller for projects
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[explore show]

  before_action :set_project, except: %i[index explore new create]

  layout 'project'

  # GET /projects
  def index
    render_projects(params[:joined].present? ? :joined : :own)
  end

  def explore
    render_projects(:explore)
  end

  # GET /projects/1
  def show; end

  # GET /projects/new
  def new; end

  # POST /projects
  def create
    @project = current_user.projects.build(project_params)
    @project.save ? project_success('Project Created') : project_fail
  end

  # PATCH/PUT /projects/1
  def update
    return project_fail unless @project.update(project_params)

    project_success('Project Updated')
  end

  def change_status
    msg = case params[:status]
          when 'completed'
            'Project Archived'
          when 'active'
            @project.appeals.application.destroy_all
            @project.completed? ? 'Project Activated' : 'Project Closed'
          when 'open'
            'Project Opened'
          end

    @project.update(status: params[:status]) ? project_success(msg) : project_fail
  end

  def count
    return head :bad_request unless %w[task application].include?(params[:type])

    render json: {
      count: case params[:type]
             when 'task' then @project.tasks.where('percentage < 100').size
             when 'application' then @project.appeals.size
             end
    }
  end

  private

  def set_project
    @project = Project.includes(:teams, :tasks)
                      .find(params[:id])
    authorize! @project, with: ProjectPolicy
  end

  def project_params
    params.require(:project).permit(%i[name description visibility category_id avatar])
  end

  def render_projects(policy_scope)
    @pagy, projects = pagy(authorized_scope(Project.search(params), as: policy_scope))
    @html = view_to_html_string('projects/_projects', projects: projects)

    respond_to do |format|
      format.html
      format.json { render json: { html: @html, total: @pagy.count } }
    end
  end

  def project_success(message)
    @project.appeals.delete_all if @project.completed?
    flash[:toast_success] = message
    render js: "window.location = '#{project_path(@project)}'"
  end

  def project_fail(message = @project.errors.full_messages)
    render json: { message: message }, status: :unprocessable_entity
  end
end

app/views/projects/_applications.haml
#application
  - if @project.completed?
    .notification.is-warning.has-text-centered
      Project is completed. New users cannot be added.
  - else
    - if @project.visibility || @project.open?
      .columns
        .column.is-4
          %h4.title.is-4 Application: #{@project.open? ? 'Open' : 'Closed'}
        .column.content
          - if @project.open?
            %p All join requests will be rejected if you close application
            = button_to 'Close application', change_status_project_path(@project, status: 'active'), method: :patch, remote: true,
              data: { confirm: 'Are you sure?', disable: true }, class: 'button is-warning', form: { '@ajax:error': 'ajaxError' }
          - elsif @project.active?
            %p Other users can start sending join request when the application is open
            = button_to 'Open application', change_status_project_path(@project, status: 'open'), method: :patch, remote: true,
              data: { confirm: 'Are you sure?', disable: true  }, class: 'button', form: { '@ajax:error': 'ajaxError' }
    - if @project.applicable? || @project.appeals.application.exists?
      .columns
        .column.is-4
          %h4.title.is-4 Join Requests
        .column
          %application-table
    .columns
      .column.is-4
        %h4.title.is-4 Invite Users
      .column
        %invitation-table

app/views/projects/_members.haml
.container
  %section
    .container
      .columns.is-vcentered
        .column
          %h1.title.is-2
            Members
        .column.is-narrow
          - if (allowed_to? :manage?, @project) && !@project.completed?
            .buttons.has-addons
              = link_to project_manage_index_path(@project.id), class: 'button is-info' do
                %p Manage Teams
                %span.icon
                  %span.iconify{ 'data-icon': 'ant-design:tool-filled' }
              = link_to new_project_team_path(@project), class: 'button is-primary' do
                %p New Team
                %span.icon
                  %span.iconify{ 'data-icon': 'el:plus' }
      .content
        %p.has-text-grey
          - if @project.users.empty?
            No members. Invite some to Get Started!
          - else
            Total Members
            = @project.users.size
            \/
            = @project.user.license.member_limit
      .columns.is-multiline.is-mobile
        - @project.teams.each do |team|
          .column.is-half-tablet.is-one-third-desktop
            .card
              %header.card-header
                %p.card-header-title
                  = team.name
                  %span.icon{ '@click': "teamModal(#{team.id},#{@project.id})" }
                    %span.iconify{ 'data-icon': 'ant-design:info-circle-outlined' }
                .card-header-icon
                  - if team.users.empty?
                    No Members
                  - elsif team.name != 'Unassigned'
                    = team.users.size
                    \/
                    = team.team_size
                    Members
                  - else
                    = team.users.size
                    Unassigned Members

app/views/projects/_projects.haml
#project-list-holder
  - if projects.blank?
    %h4.font-semibold.has-text-centered.pt-8 No projects
  - else
    %ul
      - projects.each do |project|
        %li.project-list-item
          .project-avatar
            = link_to project do
              = project_icon(project)
          .project-details
            .flex.flex-wrap.items-center
              = link_to project, class: 'fullname' do
                %span #{project.user_name} /
                %span.font-semibold= project.name

              %p.visibility
                %span.iconify{ 'data-icon': project.visibility ? 'ic:baseline-public' : 'bx:bxs-lock-alt' }
                = project.visibility ? 'Public' : 'Private'

            %p.description= project.description[0..117] + '...'

            %a.tag.category.mr-2= project.category_name

            %span.status
              %span.status-colour{ class: project.status.downcase }
              %span= project.status.capitalize

app/views/projects/_settings.haml
#settings
  - if @project.completed?
    .notification.is-warning.has-text-centered
      Project is completed and cannot be edited.
  .columns
    .column.is-4
      %h4.title.is-4 Project Details
    .column
      = form_with model: @project, html: { '@ajax:error': 'ajaxError' } do |f|
        %fieldset{ 'disabled': @project.completed? ? 'disabled' : false }
          .flex.flex-wrap.items-center
            .pb-4{ class: 'w-1/3 md:py-4' }
              .project-avatar.is-large
                = project_icon(@project)
            .field
              %label.label Upload new avatar
              .file.has-name
                %label.file-label
                  = f.file_field :avatar, accept: 'image/png,image/jpg,image/jpeg', class: 'file-input', '@change': 'avatarChanged'
                  %span.file-cta
                    %span.file-label
                      Choose an image
                  %span.file-name
                    {{ avatarFilename }}
              %p.has-text-grey Maximum file size allowed is 200KB
          .field.my-4
            %label.label Project Title
            .control
              = f.text_field :name, class: 'input', required: ''
          .field.my-4
            %label.label Category
            .control.is-expanded
              .select.is-fullwidth
                = f.collection_select :category_id, Category.all, :id, :name
          .field.my-4
            %label.label Project Description
            .control
              = f.text_area :description, class: 'textarea'
          - if allowed_to? :change_visibility?, @project
            .field.my-4
              .control
                %label.label.required Visibility Level
                .field.flex.items-center
                  = f.radio_button :visibility, true, checked: true, required: true
                  = f.label :visibility_true, class: 'inline-flex items-center ml-2' do
                    %span.iconify.text-3xl.mr-1.flex-shrink-0{ 'data-icon': 'ic:baseline-public' }
                    %div
                      %p.font-semibold Public
                      %p.text-sm Anyone can see this project. You choose who can join.

                .field.flex.items-center
                  = f.radio_button :visibility, false
                  = f.label :visibility_false, class: 'inline-flex items-center ml-2' do
                    %span.iconify.text-3xl.mr-1.flex-shrink-0{ 'data-icon': 'bx:bxs-lock-alt' }
                    %div
                      %p.font-semibold Private
                      %p.text-sm Project access must be granted explicitly to each user.
          - unless @project.completed?
            .field.my-4
              .control
                = f.submit 'Save changes', class: 'button is-success'
  .columns
    .column.is-4
      %h4.title.is-4 Project Status
    .column
      - if @project.completed?
        %h1.title.is-5.mb-3 Unarchive project
        %p.mb-4 Unarchiving the project will restore people's ability to make changes to it.
        = button_to 'Unarchive project', change_status_project_path(@project, status: 'active'), method: :patch, remote: true,
          data: { confirm: 'Are you sure?' }, class: 'button is-warning', form: { '@ajax:error': 'ajaxError' }
      - else
        %h1.title.is-5.mb-3 Archive project
        - if @project.open?
          %p.settings-message.has-text-centered Please close the application before archiving the project
        - else
          %p.mb-4 Archiving the project will make it entirely read only. The project will be marked as completed.
          = button_to 'Archive project', change_status_project_path(@project, status: 'completed'), method: :patch, remote: true,
            data: { confirm: 'Are you sure?' }, class: 'button is-danger', form: { '@ajax:error': 'ajaxError' }

app/views/projects/_tasks.haml
#task
  %task-table{ ':project-id': @project.id, ':completed': @project.completed?, ':admin': allowed_to?(:manage?, @project), ':user-id': current_user.id }
    %template{ 'v-slot:action': '' }
      - if !@project.completed? && (allowed_to? :create_task?, @project)
        .buttons.has-addons
          = link_to 'New task', new_project_task_path(@project), class: 'button is-primary'
      - if @project.completed?
        .notification.is-warning.has-text-centered
          Project is completed. Tasks are now read-only.

app/views/projects/explore.haml
- content_for :title, 'Explore Projects'

%section.section.pt-4
  .container
    .title-holder
      %h4.title.is-4.my-4 Explore Projects
      - if user_signed_in?
        = link_to 'New Project', new_project_path, class:'button is-success ml-auto'

    %project-list{ 'init-projects-html': @html,
                   ':init-total': @pagy.count,
                   ':has-tabs': false }

app/views/projects/index.haml
- content_for :title, 'Your Projects'

%section.section.pt-4
  .container
    .title-holder
      %h4.title.is-4.my-4 Projects
      = link_to 'New project', new_project_path, class: 'button is-success ml-auto'
    %project-list{ 'init-projects-html': @html, ':init-total': @pagy.count }

app/views/projects/show.haml
- content_for :title, @project.name

%section.section
  .container
    .columns.is-vcentered
      .column.is-narrow.is-hidden-mobile
        .project-avatar.is-large
          = project_icon(@project)
      .column
        %h1.title.is-3-desktop.is-size-4-touch
          = @project.name
          - if @project.completed?
            %b-tooltip{ 'label': 'Project completed', 'position': 'is-top', 'type': 'is-info' }
              %span.icon.iconify{ 'data-icon': 'bx:bxs-check-circle' }
          - elsif @project.open?
            %b-tooltip{ 'label': 'Project is receiving applications', 'position': 'is-top', 'type': 'is-info' }
              %span.icon.iconify{ 'data-icon': 'ic:baseline-person-add' }

          - if @project.visibility
            %b-tooltip{ 'label': 'Public project', 'position': 'is-top', 'type': 'is-info' }
              %span.icon.iconify{ 'data-tooltip': 'Tooltip Text', 'data-icon': 'ic:baseline-public' }
          - else
            %b-tooltip{ 'label': 'Private project', 'position': 'is-top', 'type': 'is-info' }
              %span.icon.iconify{ 'data-icon': 'bx:bxs-lock-alt' }
        %p.subtitle.is-5-desktop.is-size-6-touch Owned by: #{@project.user.name}

      - unless current_user&.in_project?(@project) || !user_signed_in?
        .column.is-narrow
          - appeal = @project.appeals.find_by(user: current_user)
          - if appeal&.application?
            = link_to 'Cancel Application', application_path(appeal), method: :delete, remote: true,
              data: { confirm: 'Are you sure?', disable_: true }, class: 'button is-danger float-right',
              form: { '@ajax:error': 'ajaxError' }

          - elsif appeal&.invitation?
            .box
              %h1.subtitle.is-4.has-text-primary You are Invited
              .buttons
                = button_to 'Accept', accept_invitation_path(id: appeal.id, user_id: current_user.id, project_id: @project.id),
                  remote: true, data: { confirm: 'Are you sure?', disable: true }, class: 'button is-success',
                  form: { '@ajax:error': 'ajaxError' }

                = button_to 'Decline', invitation_path(appeal), method: :delete,
                  remote: true, data: { confirm: 'Are you sure?', disable: true }, class: 'button is-danger',
                  form: { '@ajax:error': 'ajaxError' }

          - elsif current_user != @project.user && @project.applicable?
            = button_to 'Join', project_applications_path(@project), class: 'button is-success float-right',
              remote: true, data: { confirm: 'Are you sure?', disable: true }, form: { '@ajax:error': 'ajaxError' }

    %b-tabs{ 'destroy-on-hide': '', ':animated': 'false', 'type': 'is-boxed', 'position': 'is-centered' }
      %b-tab-item
        %template{ 'slot': 'header' }
          %span.icon.iconify.ml-0{ 'data-icon': 'jam:users' }
          Members
        .container
          = render partial: 'members'
      - if current_user&.in_project?(@project)
        %b-tab-item
          %template{ 'slot': 'header' }
            %span.icon.iconify.ml-0{ 'data-icon': 'fe:list-task' }
            Tasks
            - if @project.tasks.size.positive?
              %b-tag{ 'rounded': '', 'v-if': 'taskCount == -1' }
                %p= @project.tasks.where('percentage < ?', 100).size
            %b-tag{ 'v-if': 'taskCount >= 0', 'rounded': '' }
              {{ taskCount }}
          .container
            = render partial: 'tasks'
      - if @project.user == current_user || current_user&.admin?
        %b-tab-item
          %template{ 'slot': 'header' }
            %span.icon.iconify.ml-0{ 'data-icon': 'mdi:application-import' }
            Applications
            - if @project.appeals.size.positive?
              %b-tag{ 'rounded': '', 'v-if': 'applicationCount == -1' }
                %p= @project.appeals.size
            %b-tag{ 'rounded': '', 'v-if': 'applicationCount > 0' }
              %p {{ applicationCount }}
          .container
            = render partial: 'applications'
        %b-tab-item{ 'label': 'Settings' }
          %template{ 'slot': 'header' }
            %span.icon.iconify.ml-0{ 'data-icon': 'ic:baseline-settings' }
            Settings
          .container
            = render partial: 'settings'