config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  # /:path
  resources :pages, path: '', only: [] do
    collection do
      get 'pricing'
      get 'about'
      get 'newsletter'
      get 'love'
      get 'feedback'
      get 'features'

      # For analytics
      post 'track_social'
      post 'track_time'
      post 'submit_feedback'
    end
  end

  scope module: :admin do
    # /metrics/:path
    resources :metrics, only: :index do
      collection do
        get 'newsletter'
        get 'traffic'
        get 'social'
      end
    end

    # /charts/:path
    resources :charts, only: [] do
      collection do
        get 'subscription_ratio'
        get 'subscription_by_date'
        get 'landing_page_feedback'

        get 'social_share_ratio'
        get 'social_share_by_date'

        get 'referrers_ratio'
        get 'referrers_by_date'
        get 'average_time_spent_per_page'
        get 'number_of_visits_per_page'

        get 'newsletter_subscription_by_date'
        get 'unsubscription_by_newsletter'
        get 'unsubscription_reason'
      end
    end

    # /newsletters/:path
    resources :newsletters, only: %i[index create new show] do
      collection do
        get 'subscribers'
        get 'unsubscribe'

        post 'subscribe'
        post 'unsubscribe', to: 'newsletters#post_unsubscribe'
      end
    end
  end

  namespace :admin do
    resources :dashboard, only: :index

    resources :categories, only: %i[index create update destroy]
    resources :skills, only: %i[index create update destroy]
  end

  resources :categories, only: :index
  resources :skills, only: :index

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # /users/:path
  resources :users, only: %i[index show] do
    member do
      get 'timeline'
    end
  end

  # /settings/:path
  scope module: :users do
    namespace :settings do
      resource :profile, only: %i[show update] do
        delete 'remove_avatar'
      end

      resource :account, only: :show do
        delete 'disconnect_omniauth'
        put 'reset_password'
      end

      resource :billing, only: %i[show update]

      resource :personality, only: %i[show update]

      resource :skills, only: %i[show create destroy]

      resource :emails, only: :show do
        post 'subscribe'
        post 'unsubscribe'
      end
    end
  end

  # /projects/:path
  resources :projects do
    get 'explore', on: :collection

    # TODO: change the name?
    member do
      get 'count'
      patch 'change_status'
    end

    scope module: :projects do
      scope module: :teams do
        resources :teams, except: %i[index]

        resources :manage, only: %i[index create] do
          collection do
            get 'suggest'
            get 'manage_data'
            post 'recompute_data'
            delete 'remove_user'
          end
        end
      end

      shallow do
        scope module: :appeals do
          resources :invitations, only: %i[index create destroy] do
            post 'accept', on: :member
          end

          resources :applications, only: %i[index create destroy] do
            post 'accept', on: :member
          end
        end
      end

      resources :tasks, except: %i[index show] do
        collection do
          get 'data'
        end

        member do
          patch 'set_percentage'
          patch 'assign_self'
        end
      end
    end
  end

  # /notifications/:path
  resources :notifications, only: %i[index destroy] do
    member do
      patch 'read'
      patch 'unread'
    end

    patch 'read_all', on: :collection
  end

  authenticated :user do
    root to: 'projects#index', as: :authenticated_root
  end

  root to: 'pages#home'
end

app/models/newsletter.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: newsletters
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Newsletter < ApplicationRecord
  # Equivalent to: has one :rich_text_content
  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true

  scope :unsubscription_by_newsletter, lambda {
    find_by_sql(
      "SELECT newsletters.title,
         newsletters.created_at, COUNT(newsletter_feedbacks)
         as feedback_count FROM newsletters JOIN newsletter_feedbacks
         ON newsletter_feedbacks.created_at BETWEEN newsletters.created_at
         AND newsletters.created_at + interval '7 days' GROUP BY newsletters.id"
    )
  }

  after_commit :send_newsletter, on: :create

  private

  def send_newsletter
    NewsletterSubscription.all_subscribed_emails.each_slice(50) do |emails|
      NewsletterMailer.send_newsletter(emails, self).deliver_later
    end
  end
end

app/controllers/admin/newsletters_controller.rb
# frozen_string_literal: true

# Controller for newsletter
class Admin::NewslettersController < Admin::BaseController
  skip_before_action :authenticate_user!, only: %i[subscribe unsubscribe post_unsubscribe]

  skip_before_action :admin_authorize, only: %i[subscribe unsubscribe post_unsubscribe]

  layout 'metrics_page', except: :unsubscribe

  def index
    @newsletters = Newsletter.select(:id, :title, :created_at)
  end

  def create
    newsletter = Newsletter.new(newsletter_params)

    if newsletter.save
      flash[:toast_success] = 'Newsletter sent'
      render js: "window.location = '#{newsletter_path(newsletter)}'"
    else
      render json: { message: 'Send Failed' }, status: :unprocessable_entity
    end
  end

  def show
    @newsletter = Newsletter.find(params[:id])

    return unless request.xhr?

    render json: { html: view_to_html_string('admin/newsletters/_modal') }
  end

  def subscribers
    @subscribers = NewsletterSubscription.where(subscribed: true)
  end

  def subscribe
    if NewsletterSubscription.subscribe(params[:email])
      render json: { message: 'Thanks for subscribing' }
    else
      render json: { message: 'Subscription Failed' }, status: :unprocessable_entity
    end
  end

  def unsubscribe; end

  def post_unsubscribe
    feedback = NewsletterFeedback.create(unsubscribe_params)

    if feedback.errors.any?
      render json: { message: feedback.errors.full_messages }, status: :unprocessable_entity
    else
      # Prevent Oracle attack on newsletter subscribers list by returning as
      # long as the params syntax are correct
      render json: { message: 'Newsletter Unsubscribed! Hope to see you again' }
    end
  end

  private

  def newsletter_params
    params.require(:newsletter).permit(:title, :content)
  end

  def unsubscribe_params
    p = params.require(:newsletter_unsubscription).permit(:email, reasons: [])

    { newsletter_subscription: NewsletterSubscription.find_by(email: p[:email]), reasons: p[:reasons] }
  end
end

app/views/admin/newsletters/_modal.haml
= @newsletter.content

app/views/admin/newsletters/index.haml
- content_for :title, 'Newsletters Archive'

%h1.title Newsletters Archive
%newsletters-table{ 'data': @newsletters.to_json }

app/views/admin/newsletters/new.haml
- content_for :title, 'Send Newsletter'

%h1.title Send Newsletter

= form_with model: Newsletter.new, html: { '@ajax:error': 'ajaxError' } do |f|
  .field
    .control
      = f.text_field :title, class: 'input', placeholder: 'Newsletter Title', required: ''
  .field
    .control
      = f.rich_text_area :content, placeholder: 'Type your newsletter here...', class: 'content'
  .field
    .control
      = f.submit 'Send newsletter', class: 'button is-primary'

app/views/admin/newsletters/show.haml
- content_for :title, @newsletter.title

%section.section
  .container
    %h3.title.is-3
      = @newsletter.title

    .content
      = @newsletter.content

app/views/admin/newsletters/subscribers.haml
- content_for :title, 'Newsletter Subscribers'

%h1.title Newsletter Subscribers
%subscribers-table{ 'initial-data': @subscribers.to_json }

app/views/admin/newsletters/unsubscribe.haml
- content_for :title, 'Unsubscribe Newsletter'

!!!
%html.has-background-grey-lighter{ lang: 'en' }
  %head
    = render 'layouts/head'

    = javascript_packs_with_chunks_tag 'landing_page', defer: ''

  %body.has-text-centered
    #landing-page
      %section.section#unsubscribe
        .container.box.has-text-centered
          .columns
            .column
              = image_tag 'logo/logo_horizontal.svg', alt: 'Diversify logo', width: 200

          %h1.title.is-3.is-spaced We are sorry to see you go
          %h3.subtitle.is-5 Please let us know why you want to unsubscribe

          .columns
            .column
              = form_with url: unsubscribe_newsletters_path, scope: :newsletter_unsubscription, html: { '@ajax:success': 'ajaxSuccess', '@ajax:error': 'ajaxError' } do |f|
                .field
                  .control
                    = f.text_field :email, class: 'input', placeholder: 'Your email address', type: 'email', required: ''

                - NewsletterFeedback::REASONS.each do |key, desc|
                  .field
                    .control
                      = f.label "reasons_#{key}", class: 'checkbox select-none' do
                        = f.check_box :reasons, { multiple: '' }, key, nil
                        = desc

                .field
                  .control.has-text-centered
                    = f.submit 'Unsubscribe', class: 'button is-primary'